<?php

function ddrupal_menu() {
  $items = array();
  $items['new_character'] = array(
    'title' => t('Create a new character?'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('start_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['new_character/race'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('race_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['new_character/class'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('class_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['new_character/rolls'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rolls_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['new_character/stats'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stats_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['new_character/skills'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('skills_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['new_character/name'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('name_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function start_form() {
  $form['submit'] = array(
      '#type' => 'submit',
      '#description' => t('Are you ready to begin?'),
      '#value' => t('Create Character'),
  );
  return $form;
}

function start_form_submit($form, &$form_state) {
  $_SESSION['new_character'] = array();
  $form_state['redirect'] = 'new_character/race';
}

function race_form() {
  $form['race'] = array(
    '#title' => t('What race is your character?'),
    '#type' => 'radios',
    '#options' => array(
      "hill_dwarf" => "Dwarf (Hill)",
      "mountain_dwarf" => "Dwarf (Mountain)",
      "high_elf" => "Elf (High)",
      "wood_elf" => "Elf (Wood)",
      "dark_elf" => "Elf (Drow)",
      "halfling" => "Halfling",
      "human" => "Human",
      "dragonborn" => "Dragonborn",
      "forest_gnome" => "Gnome (Forest)",
      "rock_gnome" => "Gnome (Rock)",
      "half_elf" => "Half-Elf",
      "half_orc" => "Half-Orc",
      "tiefling" => "Tiefling",
    ),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Set Race',
  );
  return $form;
}

function race_form_submit($form, &$form_state) {
  $_SESSION['new_character']['race'] = $form_state['values']['race'];
  $form_state['redirect'] = 'new_character/class';
}

function class_form() {
  $form['class'] = array(
    '#title' => t('What class is your character?'),
    '#type' => 'radios',
    '#options' => array(
      "barbarian" => "Barbarian",
      "bard" => "Bard",
      "cleric" => "Cleric",
      "druid" => "Druid",
      "fighter" => "Fighter",
      "monk" => "Monk",
      "paladin" => "Paladin",
      "ranger" => "Ranger",
      "rogue" => "Rogue",
      "sorcerer" => "Sorcerer",
      "warlock" => "Warlock",
      "wizard" => "Wizard",
    ),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Set Class',
  );
  return $form;
}

function class_form_submit($form, &$form_state) {
  $class = $form_state['values']['class'];
  $_SESSION['new_character']['class'] = $class;

  $query = new EntityFieldQuery();


  $entities = $query->entityCondition('entity_type', 'node')
  ->propertyCondition('type', 'class')
  ->propertyCondition('title', $class)
  ->propertyCondition('status', 0)
  ->range(0,1)
  ->execute();

  if (!empty($entities['node'])) {
    $ids = array_keys($entities['node']);
    $nid = array_shift($ids);
    $node = node_load($nid);
    $skills = array();
    foreach ($node->field_skill_proficiency['und'] as $skill_proficiency) {
      $skills[] = $skill_proficiency['value'];
    }

  $_SESSION['new_character']['skill_proficiency'] = $skills;
  $_SESSION['new_character']['total_skills'] = $node->field_total_skills['und'][0]['value'];
  }

  $form_state['redirect'] = 'new_character/rolls';
}


function element_validate_stat_range($element) {
  $test_case = $element['#value'];
  settype($test_case, 'float');
  if ($test_case != floor($test_case)) {
    form_error($element, t('Please enter a whole number.'));
  } else if ($test_case > 18 || $test_case < 4) {
    form_error($element, t('Your score must be between 4 and 18.'));
  }
}

function rolls_form() {
  $form['roll1'] = array(
    '#title' => t('Roll four 6-sided dice and add the highest 3. Do this six times and enter your results.'),
    '#description' => t('Roll 1'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['roll2'] = array(
    '#description' => t('Roll 2'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['roll3'] = array(
    '#description' => t('Roll 3'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['roll4'] = array(
    '#description' => t('Roll 4'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['roll5'] = array(
    '#description' => t('Roll 5'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['roll6'] = array(
    '#description' => t('Roll 6'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save Rolls',
  );
  return $form;
}

function rolls_form_submit($form, &$form_state) {
  $_SESSION['new_character']['rolls'] = array();
  for ($i = 1; $i <= 6; $i++) {
    $_SESSION['new_character']['rolls'][] = $form_state['values']['roll'.$i];
  }
  $form_state['redirect'] = 'new_character/stats';
}

function stats_form() {
  $rolls = $_SESSION['new_character']['rolls'];
  $stat_rolls = array();
  for ($i = 0; $i < count($rolls); $i++) {
    $opt = new stdClass();
    $opt->option = array($rolls[$i] => $rolls[$i]);
    $stat_rolls[] = $opt;
  }

  $form['strength'] = array(
    '#title' => t('Allocate your scores to each stat.'),
    '#description' => t('Strength'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['dexterity'] = array(
    '#description' => t('Dexterity'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['constitution'] = array(
    '#description' => t('Constitution'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['intelligence'] = array(
    '#description' => t('Intelligence'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['wisdom'] = array(
    '#description' => t('Wisdom'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
  );

  $form['charisma'] = array(
    '#description' => t('Charisma'),
    '#type' => 'select',
    '#options' => $stat_rolls,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_stat_range'),
    );

  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => 'Save Stats',
  );
  return $form;
}

function stats_form_submit($form, &$form_state) {
  $_SESSION['new_character']['strength'] = $form_state['values']['strength'];
  $_SESSION['new_character']['dexterity'] = $form_state['values']['dexterity'];
  $_SESSION['new_character']['constitution'] = $form_state['values']['constitution'];
  $_SESSION['new_character']['intelligence'] = $form_state['values']['intelligence'];
  $_SESSION['new_character']['wisdom'] = $form_state['values']['wisdom'];
  $_SESSION['new_character']['charisma'] = $form_state['values']['charisma'];

  echo '<pre>';
  var_dump($_SESSION['new_character']);
  echo '</pre>';
  exit;

  $form_state['redirect'] = 'new_character/skills';
}

function skills_form() {
  $skill_options = array();
}

function name_form() {
  $form['name'] = array(
    '#title' => t('What is your character\'s name?'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save Name',
  );
  return $form;
}

function name_form_submit($form, &$form_state) {
  $_SESSION['new_character']['name'] = $form_state['values']['name'];
  $form_state['redirect'] = 'node/add/character';
}
